In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from gurobipy import Model, GRB, quicksum

In [3]:
df_distances = pd.read_excel('data/distances.xlsx', sheet_name=0, header=None)

distances = df_distances.iloc[2:, 2:].to_numpy()
print(distances)

[[16.16 24.08 24.32 21.12]
 [19.0 26.47 27.24 17.33]
 [25.29 32.49 33.42 12.25]
 [0.0 7.93 8.31 36.12]
 [3.07 6.44 7.56 37.37]
 [1.22 7.51 8.19 36.29]
 [2.8 10.31 10.95 33.5]
 [2.87 5.07 5.67 38.8]
 [3.8 8.01 7.41 38.16]
 [12.35 4.52 4.35 48.27]
 [11.11 3.48 2.97 47.14]
 [21.99 22.02 24.07 39.86]
 [8.82 3.3 5.36 43.31]
 [7.93 0 2.07 43.75]
 [9.34 2.25 1.11 45.43]
 [8.31 2.07 0.0 44.43]
 [7.31 2.44 1.11 43.43]
 [7.55 0.75 1.53 43.52]
 [11.13 18.41 19.26 25.4]
 [17.49 23.44 24.76 23.21]
 [11.03 18.93 19.28 25.43]
 [36.12 43.75 44.43 0.0]]


In [4]:
df_workloads = pd.read_csv('data/bricks_index_values.csv')

workloads = df_workloads['index_value'].to_numpy()
print(workloads)

[0.1609 0.1164 0.1026 0.1516 0.0939 0.132  0.0687 0.093  0.2116 0.2529
 0.0868 0.0828 0.0975 0.8177 0.4115 0.3795 0.071  0.0427 0.1043 0.0997
 0.1698 0.2531]


In [5]:
# Current assignment (c_ij)
current_assignment = np.zeros((22, 4))
current_assignment[[0, 1, 2, 3, 4], 0] = 1
current_assignment[[5, 6, 7, 8], 1] = 1
current_assignment[[9, 10, 11, 12, 13], 2] = 1
current_assignment[[14, 15, 16, 17, 18, 19, 20, 21], 3] = 1

In [6]:
workload_min = 0.8
workload_max = 1.2